import type { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-flight',
    name: 'First Flight',
    description: 'Complete your first flight logbook entry',
    imagePrompt: 'A majestic golden badge with wings spread wide against a dawn sky, an airplane silhouette in the center, achievement medal style, warm golden light, digital art illustration',
    category: 'experience',
    icon: 'plane-takeoff',
    collected: false,
  },
  {
    id: 'cockpit-visitor',
    name: 'Cockpit Visitor',
    description: 'Special: You got to visit the cockpit!',
    imagePrompt: 'A dramatic cockpit view from inside an airplane with glowing instrument panels, sunset through the windshield, badge frame border, epic aviation art style',
    category: 'seat',
    icon: 'gauge',
    collected: false,
  },
  {
    id: 'friendly-skies',
    name: 'Friendly Skies',
    description: 'Had an amazing conversation with your seat neighbor',
    imagePrompt: 'Two friendly travelers sharing stories in comfortable airplane seats with warm cabin lighting, illustrated badge style, cozy atmosphere, watercolor digital art',
    category: 'experience',
    icon: 'users',
    collected: false,
  },
  {
    id: 'crew-favorite',
    name: 'Crew Favorite',
    description: 'Received special recognition from the flight crew',
    imagePrompt: 'A smiling flight attendant presenting a golden star to a happy passenger, airplane cabin interior, badge frame, warm professional illustration style',
    category: 'crew',
    icon: 'star',
    collected: false,
  },
  {
    id: 'timezone-hopper',
    name: 'Timezone Hopper',
    description: 'Crossed 3 or more timezones in a single flight',
    imagePrompt: 'Multiple vintage clock faces floating among clouds with an airplane trail connecting them, globe in background, achievement medal style, steampunk-inspired digital art',
    category: 'timezone',
    icon: 'clock',
    collected: false,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Completed a red-eye overnight flight',
    imagePrompt: 'A mystical owl with spread wings flying alongside an airplane under a starry night sky with aurora borealis, badge medal frame, ethereal digital illustration',
    category: 'experience',
    icon: 'moon',
    collected: false,
  },
  {
    id: 'window-watcher',
    name: 'Window Watcher',
    description: 'Logged a breathtaking view from your window seat',
    imagePrompt: 'An airplane window frame showing a spectacular view of clouds, mountains and sunrise below, camera lens border effect, photorealistic illustration badge style',
    category: 'seat',
    icon: 'eye',
    collected: false,
  },
  {
    id: 'mile-high-foodie',
    name: 'Mile High Foodie',
    description: 'Rated an in-flight meal with 5 stars',
    imagePrompt: 'An elegant in-flight meal tray with gourmet food presentation at 35000 feet, five golden stars floating above, badge frame, culinary illustration art style',
    category: 'food',
    icon: 'utensils',
    collected: false,
  },
  {
    id: 'delay-survivor',
    name: 'Delay Survivor',
    description: 'Survived a 2+ hour delay with a positive attitude',
    imagePrompt: 'A resilient traveler meditating peacefully in an airport terminal with delayed flight boards behind them, zen garden elements, achievement badge frame, calm illustration style',
    category: 'delay',
    icon: 'shield',
    collected: false,
  },
  {
    id: 'globe-trotter',
    name: 'Globe Trotter',
    description: 'Completed 5 flights total - you are a true traveler!',
    imagePrompt: 'A magnificent golden globe with airplane routes crisscrossing around it, stamps and passport marks floating around, ultimate achievement badge frame, premium illustration style',
    category: 'experience',
    icon: 'globe',
    collected: false,
  },
]
